### PR TITLE
Social selection fix

### LINKED ISSUE #53: SegmentedControl in SocialViewController slipping under Toolbar in iOS <11.0
Looks like the segmentedControl hides under the toolbar for example on iOS 10.3.1
Screenshot 2019-03-12 at 16 06 26

### PR DESCRIPTION
**Pull request by mltbnz**
## Thank you for your contribution! 

This PR will fix #53 

Before:
Screenshot 2019-06-24 at 08 38 05

After:
Screenshot 2019-06-24 at 08 39 06

### Before merging the PR

- [ ] If applicable, does the PR contain enough unit / UI tests?
- [ ] If applicable, did you add a before / after screenshot of the feature?
- [x] Did you update the [CHANGELOG.md](https://github.com/criticalmaps/criticalmaps-ios/blob/master/CHANGELOG.md)?

### CODE REVIEW

File: CriticalMass/AppController.swift [hunk 1]
```diff
@@ -60,7 +60,7 @@ class AppController {
     }
 
     private func getSocialViewController() -> SocialViewController {
-        return SocialViewController(chatViewController: getChatViewController, twitterViewController: getTwitterViewController)
+        return SocialViewController(chatViewController: getChatViewController(), twitterViewController: getTwitterViewController())
```
Comment (lennet) [inline CriticalMass/AppController.swift]: What are the benefits here from removing the lazy loading?

Comment (mltbnz) [reply CriticalMass/AppController.swift]: I don't see why they should be lazy. Actually I just changed the property inside the SocialController to be a `let` rarther then to be a closure so it makes code more readable in my eyes. What is the benefit here of having them lazy? It does not need to capture the AppController instance, right? Would opt-in for constants there anyhow I think

File: CHANGELOG.md [hunk 2]
```diff
@@ -13,6 +13,7 @@ Changelog for Critical Maps iOS
 
 ### Fixed
 
+- SocialSegment sliding under NavigationBar bug in iOS 10
```
Comment (lennet) [inline CHANGELOG.md]: This should be added to Unreleased

File: CriticalMass/AppController.swift (hunk 1 above)
Comment (lennet) [reply CriticalMass/AppController.swift]: Mostly smaller memory optimizations. By loading the content lazily only the current content is in memory and on switching the tab the old content get's released

File: CHANGELOG.md (hunk 2 above)
Comment (mltbnz) [reply CHANGELOG.md]: Ups. Thought I did

File: CriticalMass/AppController.swift (hunk 1 above)
Comment (mltbnz) [reply CriticalMass/AppController.swift]: Hmm. That is true. Might also happen the user never opens the socialController. So that could be saved. I do think though that the pattern is mostly used for computational heavy allocations and if some properties are only there after initialization of the object that holds the lazy var. Did you ever profile the memory?

File: CHANGELOG.md (hunk 2 above)
Comment (mltbnz) [reply CHANGELOG.md]: Think it is:
https://github.com/mltbnz/criticalmaps-ios/blob/socialSelectionFix/CHANGELOG.md
