### PR TITLE
Fix whitespace only chat message and rework chatInputView a little

### LINKED ISSUE #173: Chat should not be able to send whitespace
My idea for the fix: Adding whitespace in the chat should enable the send button but if only whitespace has been added the send event should not trigger the post request.

### PR DESCRIPTION
**Pull request by mltbnz**
* renaming for clarity
* using layout anchors
* gate send event with check if text isEmpty and does not only contain of whitespace

### Before merging the PR

- [ ] If applicable, does the PR contain enough unit / UI tests?
- [ ] If applicable, did you add a before / after screenshot of the feature?
- [x] Did you update the [CHANGELOG.md](https://github.com/criticalmaps/criticalmaps-ios/blob/master/CHANGELOG.md)?

closes #173

### CODE REVIEW

File: CriticalMass/ChatInputView.swift [hunk 1]
```diff
@@ -12,25 +12,29 @@ protocol ChatInputDelegate: AnyObject {
 }
 
 class ChatInputView: UIView, UITextFieldDelegate {
+    struct Constants {
+        static let textFieldHeight = CGFloat(46.0)
```
Comment (lennet) [inline CriticalMass/ChatInputView.swift]: Does that work with dynamic type?

File: CriticalMass/ChatInputView.swift [hunk 2]
```diff
@@ -70,11 +83,10 @@ class ChatInputView: UIView, UITextFieldDelegate {
     }
 
     private func commonInit() {
-        addSubview(textField)
-        addSubview(button)
+        addSubview(chatStack)
         addSubview(separator)
 
-        textField.delegate = self
+        messageTextField.addTarget(self, action: #selector(didTapSendButton), for: .editingDidEndOnExit)
```
Comment (lennet) [inline CriticalMass/ChatInputView.swift]: Cool! Never seen that API before

File: CriticalMass/ChatInputView.swift (hunk 1 above)
Comment (mltbnz) [reply CriticalMass/ChatInputView.swift]: That is a good question. I have not tried tbh. Never saw out in the os but I always thought why is no search bar or whatsoever updated with a bigger font. I will take a look in what is possible there

Comment (lennet) [reply CriticalMass/ChatInputView.swift]: PNG-Bild
Just checked iMessage and the text input gets updated. But if just seen that we are not supporting it in the current version of the app so its finde that this PR isn‘t changing that. We just should make sure that nothing is broken but it doesn’t need to scale for now

Comment (mltbnz) [reply CriticalMass/ChatInputView.swift]: Also safari supports it in the url textfield. Maybe we can create an issue for it. Would be cool if we support it

**Comment by mltbnz** [comment]
I figured that the PR has an issue when entering a lot of text. I am not setting a sendButton width constraint and that makes the send Button disappear. When I add a constraint works nice but I figured that longer strings like in french make textField very small especially on smaller devices. So maybe we could switch from a string button to an icon button.
What do you think @zutrinken ?

**Comment by lennet** [comment]
Maybe setting a maxwidth and truncate the text if needed?

**Comment by mltbnz** [comment]
I have set a fixed width that works with our localisations. The finnish translation `lähettää` for example would be truncated

**Comment by zutrinken** [comment]
@mltbnz ja, let's do button like iMessage. I'll update the design.

**Comment by zutrinken** [comment]
@mltbnz does this work for you?

<table><tr><td></td><td></td></tr></table>

**Comment by mltbnz** [comment]
I like it
